name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: canopennodezephyr
          submodules: true
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: canopennodezephyr
          toolchains: arm-zephyr-eabi:x86_64-zephyr-elf
          ccache-cache-key: ${{ matrix.os }}

      - name: Build firmware
        working-directory: canopennodezephyr
        shell: bash
        run: |
          west twister -T samples/canopennode -v --inline-logs --integration

      - name: Print ccache stats
        if: runner.os != 'Windows'
        run: |
          ccache -s -vv
